/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtsAnalyzerRouteImport } from './routes/ats-analyzer'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ImportRouteImport } from './routes/import'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TailorRouteImport } from './routes/tailor'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EditorResumeIdRouteImport } from './routes/editor.$resumeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsAnalyzerRoute = AtsAnalyzerRouteImport.update({
  id: '/ats-analyzer',
  path: '/ats-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorRoute = TailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorResumeIdRoute = EditorResumeIdRouteImport.update({
  id: '/editor/$resumeId',
  path: '/editor/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ats-analyzer': typeof AtsAnalyzerRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/import': typeof ImportRoute
  '/privacy': typeof PrivacyRoute
  '/tailor': typeof TailorRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/editor/$resumeId': typeof EditorResumeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ats-analyzer': typeof AtsAnalyzerRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/import': typeof ImportRoute
  '/privacy': typeof PrivacyRoute
  '/tailor': typeof TailorRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/editor/$resumeId': typeof EditorResumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ats-analyzer': typeof AtsAnalyzerRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/import': typeof ImportRoute
  '/privacy': typeof PrivacyRoute
  '/tailor': typeof TailorRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/editor/$resumeId': typeof EditorResumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ats-analyzer'
    | '/builder'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/how-it-works'
    | '/import'
    | '/privacy'
    | '/tailor'
    | '/templates'
    | '/terms'
    | '/editor/$resumeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ats-analyzer'
    | '/builder'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/how-it-works'
    | '/import'
    | '/privacy'
    | '/tailor'
    | '/templates'
    | '/terms'
    | '/editor/$resumeId'
  id:
    | '__root__'
    | '/'
    | '/ats-analyzer'
    | '/builder'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/how-it-works'
    | '/import'
    | '/privacy'
    | '/tailor'
    | '/templates'
    | '/terms'
    | '/editor/$resumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsAnalyzerRoute: typeof AtsAnalyzerRoute
  BuilderRoute: typeof BuilderRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ImportRoute: typeof ImportRoute
  PrivacyRoute: typeof PrivacyRoute
  TailorRoute: typeof TailorRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  EditorResumeIdRoute: typeof EditorResumeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-analyzer': {
      id: '/ats-analyzer'
      path: '/ats-analyzer'
      fullPath: '/ats-analyzer'
      preLoaderRoute: typeof AtsAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor': {
      id: '/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof TailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$resumeId': {
      id: '/editor/$resumeId'
      path: '/editor/$resumeId'
      fullPath: '/editor/$resumeId'
      preLoaderRoute: typeof EditorResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsAnalyzerRoute: AtsAnalyzerRoute,
  BuilderRoute: BuilderRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ImportRoute: ImportRoute,
  PrivacyRoute: PrivacyRoute,
  TailorRoute: TailorRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  EditorResumeIdRoute: EditorResumeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
